# Generated by Django 5.1.7 on 2025-03-27 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuenta',
            name='id_cliente',
        ),
        migrations.RemoveField(
            model_name='cuenta',
            name='id_mesero',
        ),
        migrations.RemoveField(
            model_name='cuenta',
            name='id_plato',
        ),
        migrations.RemoveField(
            model_name='cuenta',
            name='id_venta',
        ),
        migrations.AlterField(
            model_name='venta',
            name='tipo_venta',
            field=models.CharField(choices=[('Caja', 'Venta en Caja')], default='Caja', max_length=6, verbose_name='Tipo de Venta'),
        ),
        migrations.DeleteModel(
            name='Mesero',
        ),
        migrations.DeleteModel(
            name='Plato',
        ),
        migrations.DeleteModel(
            name='Cuenta',
        ),
    ]
