# Generated by Django 5.1.7 on 2025-04-01 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_verificador_remove_cuenta_id_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentacion',
            name='unidad_medida',
            field=models.CharField(choices=[('Color', 'C')], default='', max_length=12, verbose_name='Unidad de medida'),
        ),
    ]
