# Generated by Django 5.2.1 on 2025-05-09 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_proveedor_facturaproveedor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facturaproveedor',
            options={'verbose_name': 'Factura de Proveedor', 'verbose_name_plural': 'Facturas de Proveedores'},
        ),
        migrations.RemoveField(
            model_name='facturaproveedor',
            name='fecha_emision',
        ),
        migrations.RemoveField(
            model_name='facturaproveedor',
            name='fecha_vencimiento',
        ),
        migrations.RemoveField(
            model_name='facturaproveedor',
            name='proveedor',
        ),
    ]
