# Generated by Django 5.1.7 on 2025-04-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_presentacion_unidad_medida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentacion',
            name='unidad_medida',
            field=models.CharField(choices=[('Azul', 'A'), ('Negro', 'N'), ('Rojo', 'R'), ('Verde', 'V')], default='', max_length=12, verbose_name='Unidad de medida'),
        ),
    ]
