# Generated by Django 5.1.7 on 2025-04-01 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_presentacion_unidad_medida'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='presentacion',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='presentacion',
            name='unidad_medida',
        ),
    ]
