# Generated by Django 5.2.1 on 2025-05-09 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_facturaproveedor_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaproveedor',
            name='proveedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='app.proveedor'),
            preserve_default=False,
        ),
    ]
