# Generated by Django 5.1.7 on 2025-04-01 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_presentacion_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_venta',
            name='subtotal_venta',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=10, verbose_name='Subtotal'),
        ),
    ]
