# Generated by Django 5.1.7 on 2025-04-01 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_detalle_venta_subtotal_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_venta',
            name='subtotal_venta',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=11, verbose_name='Subtotal'),
        ),
    ]
