# Generated by Django 5.2.1 on 2025-05-10 17:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_factura_delete_facturaproveedor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factura',
            old_name='monto_total',
            new_name='valor_total',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='archivo_pdf',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='fecha_emision',
        ),
        migrations.AddField(
            model_name='factura',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='facturas_pdfs/'),
        ),
        migrations.AddField(
            model_name='factura',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factura',
            name='valor_abonado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
