# Generated by Django 5.2.1 on 2025-05-10 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_monto_total_factura_valor_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='valor_abonado',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
