# Generated by Django 5.2 on 2025-04-06 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_detalle_venta_subtotal_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='NumVerificador',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Valor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='NumVerificador'),
        ),
    ]
