# Generated by Django 5.2.1 on 2025-05-10 19:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_factura_valor_abonado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='facturas_pdfs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
