# Generated by Django 5.2 on 2025-04-06 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_producto_numverificador_alter_producto_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='NumVerificador',
            field=models.PositiveIntegerField(verbose_name='NumVerificador'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor'),
        ),
    ]
