# Generated by Django 5.2.1 on 2025-05-10 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_factura_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='nombre',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre'),
        ),
    ]
