# Generated by Django 5.2 on 2025-04-07 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_producto_numverificador_alter_producto_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='NumVerificador',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
