# Generated by Django 5.2.1 on 2025-05-26 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_proveedor_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='id_marca',
        ),
        migrations.DeleteModel(
            name='Marca',
        ),
    ]
