# Generated by Django 5.2 on 2025-04-07 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_producto_numverificador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='NumVerificador',
            field=models.PositiveIntegerField(verbose_name='NumVerificador'),
        ),
    ]
