# Generated by Django 5.2 on 2025-04-08 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_producto_numverificador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='NumVerificador',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='NumVerificador'),
        ),
    ]
