# Generated by Django 5.2.1 on 2025-05-26 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_producto_id_marca_delete_marca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='telefono',
        ),
    ]
