# Generated by Django 5.2 on 2025-04-08 10:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_producto_numverificador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='NumVerificador',
            field=models.BigIntegerField(validators=[django.core.validators.MinValueValidator(10000000000000), django.core.validators.MaxValueValidator(99999999999999)], verbose_name='NumVerificador'),
        ),
    ]
