# Generated by Django 5.2.1 on 2025-05-26 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_factura_cancelada_manual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='cancelada_manual',
        ),
    ]
