# Generated by Django 5.2.1 on 2025-05-26 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_factura_cancelada_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='cancelada_manual',
            field=models.BooleanField(default=False, verbose_name='Cancelada manualmente'),
        ),
    ]
