# Generated by Django 5.2 on 2025-04-08 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_producto_numverificador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='valor',
        ),
    ]
