# Generated by Django 5.2 on 2025-04-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_producto_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Valor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='NumVerificador',
            field=models.BigIntegerField(unique=True, verbose_name='NumVerificador'),
        ),
    ]
