# Generated by Django 5.2.1 on 2025-05-26 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_factura_cancelada_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='cancelada',
            field=models.BooleanField(default=False, verbose_name='Cancelada'),
        ),
    ]
