# Generated by Django 5.2.1 on 2025-05-27 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_proveedor_cancelada'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='telefono',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Teléfono'),
        ),
    ]
