# Generated by Django 5.2 on 2025-04-21 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_producto_fecha_creacion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
