# Generated by Django 5.2.1 on 2025-05-30 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_producto_porcentaje_ganancia_producto_precio_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio_venta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio de venta'),
        ),
    ]
