# Generated by Django 5.2.2 on 2025-06-17 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_producto_stock_minimo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='stock_minimo',
            field=models.PositiveIntegerField(default=3, verbose_name='Stock mínimo'),
        ),
    ]
