# Generated by Django 5.2.3 on 2025-06-19 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='id_cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.cliente', verbose_name='Cliente'),
        ),
    ]
